# base image is ubuntu latest version
FROM ubuntu:latest 
# install nfdump and some tools: apt-utils for  apt-get,  iputils for ifconfig,  net-tools for ping
RUN apt-get update && apt-get install -y nfdump 
#    apt-utils \
#    iputils-ping \
#    net-tools \
#    nfdump


#RUN apt-get update && apt-get install -y \
#    apt-utils \
#    iputils-ping \
#    net-tools \
#    nfdump

# expose port
EXPOSE 2055
#
ENTRYPOINT ["/usr/bin/nfcapd","-l","/var/cache/nfdump","-p","2055"]



	
