# load ubuntu image 
FROM ubuntu:latest 

# environement variables 
ENV FLOW_COLLECTOR="localhost"
ENV COLLECTOR_PORT="2055"
ENV INTERFACE="eth0"

# install fprobe
RUN apt-get update && apt-get install -y  fprobe 

# run fprobe and bin/bash
ENTRYPOINT fprobe -i${INTERFACE} ${FLOW_COLLECTOR}:${COLLECTOR_PORT} && /bin/bash                                                        
