# base image is ubuntu latest version
FROM ubuntu:latest 

# install nfdump tool
RUN apt-get update && apt-get install -y nfdump 

# expose container netflow collector port
EXPOSE 2055
 
# configure folder to store netflow data files  and start collector   
ENTRYPOINT ["/usr/bin/nfcapd","-l","/var/cache/nfdump","-p","2055"]



	
